apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
      - name: simple-node
        image: ${DOCKERHUB_REPO}:${IMAGE_TAG}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
spec:
  selector:
    app: simple-node
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000
