version: "3.8"

services:
  web:
    image: "${DOCKERHUB_REPO}:${IMAGE_TAG}"
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    environment:
      - APP_VERSION=${IMAGE_TAG}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
